### ISSUE TITLE
CUDA error: no kernel image is available for excecution on the device

### ISSUE THREAD

**Issue by Mikerov** [matteo-ronchetti/torch-radon#34]
I am receiving the following error when running the simple fbp example when caclulating the sinogram:

```
RuntimeError: CUDA error: no kernel image is available for execution on the device
```

My setup:
Nvidia GPU A6000
Pytorch 1.11.0 py3.9 cuda11.3 cudnn8.2.0.0
Cudatoolkit 11.3.1
Cudatoolkit-dev 11.4.1 - needed it to build TorchRadon from source

Torchradon was build without issues. Simple PyTorch calculations do not produce this error.

**Comment by matteo-ronchetti** [comment]
I think that the problem is because TorchRadon was not compiled for Compute Capability 80. I have update the code.
Can you try pulling the latest master and recompile it?

**Comment by Mikerov** [comment]
The latest master fixed the issue.
Your very quick response and fix are very appreciated!
