### ISSUE TITLE
make: *** No rule to make target `install'.  Stop.

### ISSUE THREAD

**Issue by henanjun** [matteo-ronchetti/torch-radon#4]
Hi, I encounter a problem of "make: *** No rule to make target `install'.  Stop." when I used "make install" . 

Could you please help me to solve it. Thanks a lot. Hope Receive you reply soon.

**Comment by matteo-ronchetti** [comment]
Hi, sorry I've removed the makefile but forgot to change the readme accordingly. 
You should install the library by running `python setup.py install` instead of `make install`.
Please let me know if this solves your issue.
