### ISSUE TITLE
ImportError: `GLIBC_2.27' not found

### ISSUE THREAD

**Issue by knxie** [matteo-ronchetti/torch-radon#5]
Hi, after installing torch-radon successfully, I encountered a problem, 
"
File "/usr/local/lib64/python3.6/site-packages/torch_radon/__init__.py", line 6, in <module>
    import torch_radon_cuda
ImportError: /usr/lib64/libm.so.6: version `GLIBC_2.27' not found (required by /usr/local/lib64/python3.6/site-packages/torch_radon_cuda.cpython-36m-x86_64-linux-gnu.so)
"
My env is -python3.6-cuda10.1-cudnn7.6-pytorch1.5.

I wonder if this problem is caused since the origin .whl is compiled on a higher-vision of Linux.

Could you help me fix this problem？ thanks!

**Comment by matteo-ronchetti** [comment]
I tried adding the "-static" flag to the compilation commands, I thinks this will fix your problem. I just pushed the code, in like 30min the new packages will be compiled and uploaded. Please try reinstalling the library (you may need to add "--force-reinstall" to the pip to actually reinstall) and let me know if this actually fixed the problem.

**Comment by knxie** [comment]
> I tried adding the "-static" flag to the compilation commands, I thinks this will fix your problem. I just pushed the code, in like 30min the new packages will be compiled and uploaded. Please try reinstalling the library (you may need to add "--force-reinstall" to the pip to actually reinstall) and let me know if this actually fixed the problem.

---  fixed it! Thanks!!

**Comment by matteo-ronchetti** [comment]
Nice!
Thank you for pointing out this issue.
