### ISSUE TITLE
Publication

### ISSUE THREAD

**Issue by fschiffers** [matteo-ronchetti/torch-radon#7]
Hello,
do you have a publication for this package that we could cite?
Best,
Florian

**Comment by matteo-ronchetti** [comment]
Hi, I'm actually working on the publication, I think I will be able to upload a first version on ArXiv next week.
What are you using this library for? Do you have any feature request?

Matteo

**Comment by fschiffers** [comment]
Hi Matteo,

that's great! We're going to cite your ArXiV paper then! 

We're using the library currently for having diff'able operators for learning. We're not making too much use of it right now, but your framework is really easy to use. You've done a really good job.

I assume that in the future you're going to include cone-beam operators as well. If this feature is coming at some point, it would be great if there would be a straight forward to define custom-trajectories using projection matrices. 

Best,
Florian

**Comment by matteo-ronchetti** [comment]
The paper is available on arXiv (https://arxiv.org/abs/2009.14788)
Here is the bibtex for citing it:
```
@misc{torch_radon,
Author = {Matteo Ronchetti},
Title = {TorchRadon: Fast Differentiable Routines for Computed Tomography},
Year = {2020},
Eprint = {arXiv:2009.14788},
}
```
